// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/8/2024, 12:53:18 AM
const configMerger = require("C:/Users/jacks/OneDrive/Documentos/Arquitectura de Informacion/Proyecto_01_Jack_Caleb/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/jacks/OneDrive/Documentos/Arquitectura de Informacion/Proyecto_01_Jack_Caleb/components/**/*.{vue,js,mjs}","C:/Users/jacks/OneDrive/Documentos/Arquitectura de Informacion/Proyecto_01_Jack_Caleb/components/**/*.{vue,js,mjs}","C:/Users/jacks/OneDrive/Documentos/Arquitectura de Informacion/Proyecto_01_Jack_Caleb/components/global//**/*.{vue,js,mjs}","C:/Users/jacks/OneDrive/Documentos/Arquitectura de Informacion/Proyecto_01_Jack_Caleb/layouts/**/*.{vue,js,mjs}","C:/Users/jacks/OneDrive/Documentos/Arquitectura de Informacion/Proyecto_01_Jack_Caleb/pages/**/*.{vue,js,mjs}","C:/Users/jacks/OneDrive/Documentos/Arquitectura de Informacion/Proyecto_01_Jack_Caleb/composables/**/*.{js,ts,mjs}","C:/Users/jacks/OneDrive/Documentos/Arquitectura de Informacion/Proyecto_01_Jack_Caleb/utils/**/*.{js,ts,mjs}","C:/Users/jacks/OneDrive/Documentos/Arquitectura de Informacion/Proyecto_01_Jack_Caleb/{A,a}pp.{vue,js,mjs}","C:/Users/jacks/OneDrive/Documentos/Arquitectura de Informacion/Proyecto_01_Jack_Caleb/{E,e}rror.{vue,js,mjs}","C:/Users/jacks/OneDrive/Documentos/Arquitectura de Informacion/Proyecto_01_Jack_Caleb/app.config.{js,ts,mjs}"] }));

module.exports = config
